# Generated by Django 3.2 on 2024-10-24 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20241023_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Поле может содержать только латинские буквы, цифры, "-", и "_"', regex='^[-a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Поле может содержать только латинские буквы, цифры, "-", и "_"', regex='^[-a-zA-Z0-9_]+$')]),
        ),
    ]
